=== atr86/All-Ocassion-Codes/Learning XML/11_st.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<!-- Root wrapper for multiple students -->
	<xsd:element name="students">
		<xsd:complexType name="students">
			<xsd:sequence>
				<xsd:element name="student" type="studentType" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="studentType">
		<xsd:sequence>
			<xsd:element name="rollnumber" type="xsd:string"/>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="marks" type="xsd:integer"/>
			<xsd:element name="result" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>

</xsd:schema>

=== atr86/All-Ocassion-Codes/Learning XML/10_student.xml
<?xml version="1.0"?>
<!-- <root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="11_st.xsd"> -->
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="11_st.xsd">
	<student>
		<rollnumber>95A0</rollnumber>
		<name>aaa</name>
		<marks>500</marks>
		<result>Firstclass</result>
	</student>
	<student>
		<rollnumber>95A1</rollnumber>
		<name>bbb</name>
		<marks>450</marks>
		<result>Firstclass</result>
	</student>
</students>
<!-- </root> -->
